[profile.default]
src                    = "src"
out                    = "out"
libs                   = ["lib"]
auto_detect_remappings = false
remappings             = ["@openzeppelin=node_modules/@openzeppelin/contracts", "forge-std/=lib/forge-std/src/"]
optimizer              = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
